"""
SQLAlchemy ORM models (async-style, sqlalchemy.ext.asyncio compatible).

ASSUMPTION: "status" is stored as a plain VARCHAR with a CHECK constraint
restricting it to the three allowed values, rather than a native SQL ENUM
type — this keeps it portable if the store is ever swapped from SQLite to
another DB, and SQLite has no native enum type anyway.

ASSUMPTION: a "duplicate book" means the same title AND the same author,
compared case-insensitively (e.g. "Dune"/"dune" by "Frank Herbert" are the
same book; "Dune" with no author is a different entry from "Dune" by a named
author). This is enforced with a DB-level UNIQUE constraint (not just an
app-level check) so it also holds under concurrent requests.

ASSUMPTION: author has no NULL/None value at the storage layer — SQLite
treats every NULL as distinct, which would silently defeat a UNIQUE
constraint for authorless books. Instead, "no author" is stored as an empty
string and translated back to None at the schema boundary
(app/schemas/book.py), so the DB constraint stays meaningful.

ASSUMPTION: created_at/updated_at are set by the DB (server_default /
server_onupdate), not by application code, so they stay correct regardless
of which code path writes a row (this endpoint, a future update endpoint,
or a manual migration script). Indexes on title, author, status, and
created_at are added up front for the future list/filter/search endpoint
mentioned in the project brief, even though this slice only adds rows.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, Index, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.config import Base


class BookStatus(str, enum.Enum):
    TO_READ = "to-read"
    READING = "reading"
    DONE = "done"


class Book(Base):
    __tablename__ = "books"
    __table_args__ = (
        CheckConstraint(
            "status IN ('to-read', 'reading', 'done')",
            name="ck_books_status_valid",
        ),
        UniqueConstraint("title", "author", name="uq_books_title_author"),
        # Separate single-column indexes (beyond the composite unique index
        # above) so lookups/filters on any one of these columns alone —
        # title search, author search, status filter, newest-first sort —
        # can use an index instead of a full table scan.
        Index("ix_books_title", "title"),
        Index("ix_books_author", "author"),
        Index("ix_books_status", "status"),
        Index("ix_books_created_at", "created_at"),
    )

    # ASSUMPTION: id is a UUID string generated by the app (not an auto-increment
    # int) so ids are stable/unique even if other engineers later merge stores
    # or generate books from multiple processes.
    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    # NOCASE collation makes both the UNIQUE constraint above and any future
    # equality lookups case-insensitive at the DB level (SQLite-specific).
    title: Mapped[str] = mapped_column(String(500, collation="NOCASE"), nullable=False)
    author: Mapped[str] = mapped_column(
        String(300, collation="NOCASE"), nullable=False, default=""
    )
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    # NOTE: SQLite has no native "ON UPDATE CURRENT_TIMESTAMP" column feature
    # (unlike e.g. MySQL), so `onupdate=func.now()` is used instead — this is
    # a SQLAlchemy-side clause that gets sent as part of any UPDATE statement
    # issued through this ORM model, and works consistently across DBs.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )
